### ISSUE TITLE
Install the Chaincode

### ISSUE THREAD

**Issue by pumicerD** [pumicerD/blockchain_booking#10]
The **chaincode** is tied to a specific Asset (RentalAsset *i.e. house, appartment, etc...).

At the moment the **chaincode** only needs to feature the following functionalities :
* book a date

**Comment by pumicerD** [comment]
See [Fabric Chaincode Java Tutorial](https://github.com/hyperledger/fabric-chaincode-java/blob/release-1.3/TUTORIAL.md)

**Comment by viktoriya-kutsarova** [comment]
Installation of chaincode is done using the fabric sdk. Critical part - in the project for the chlaincode, a specific META-INF folder should be added.
