### ISSUE TITLE
Add a second OTA to the system

### ISSUE THREAD

**Issue by viktoriya-kutsarova** [pumicerD/blockchain_booking#6]
Add a client, peer and order nodes for a second OTA

**Comment by pumicerD** [comment]
1. add a new **Organization** to `hyperledger/crypto-config.yaml`
2. add a new **Organization** to `hyperledger/configtx.yaml`, update the **Profiles** and **Channel** settings
3. update `hyperledger/docker-compose.yaml` to create peer and client nodes for the new OTA
4. update `hyperledger/base/docker-compose-base.yaml` to reflect the changes
5. update the **chaincode** Access Control Policy to grant the new OTA access
